apiVersion: v1
kind: Service
metadata:
  name: simpleapi
  namespace: default
spec:
  selector:
    app: simpleapi
  type: LoadBalancer
  ports:
    - name: simpleapi-port
      protocol: TCP
      port: 80
      targetPort: 3000
  loadBalancerIP: 192.168.1.123